---
abstract: 'A Client to access the Babel web service.'
author:
  - 'Victor Cassen <phonybone@gmail.com>'
build_requires:
  Test::More: 0
  t::Build: 0
  t::lib: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Babel-Client
provides:
  Data::Babel::Client:
    file: lib/Data/Babel/Client.pm
    version: 0.01_02
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_03
